<script>
    function addition(a, b) {
        return new Promise((resolve,reject) => {
            setTimeout(() => {
                if (a + b > 0) {
                    resolve(a + b)
                } else {
                    reject("failed")
                }

            },2000)

        })
    }

    function display(input) {
        return new Promise((resolve,reject) => {
            if(input>20){
                resolve(`the final addition is ${input}`)
            }else{
                reject(`the value is less than 20`)
            }
            
        })
    }

    /*addition(3,4).then((result)=>{
        return display(result);
    },(error)=>{
    console.log(error)
    }).then((result)=>{
        console.log(result)
    },(error)=>{
    console.log(error)})*///creates mess 


    async function result() {
        try{
        let inputOne = await addition(30, 4);//after this execution only other or below code is executed
        console.log("addition value", inputOne)
        let inputTwo = await display(inputOne);
        console.log(inputTwo)
        }catch(error){
            console.log(error)
        }
        
    }

    result()
</script>